apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-foundation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  # The template part of the deployment yaml file is a Pod configs
  template:
    metadata:
      name: react-foundation-app
      labels:
        component: web
    spec:
      containers:
        - name: react-foundation-app
          image: andyningli/react-foundation:fixed
          ports:
            - containerPort: 3000

